pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               echo "Hi"
            }
        }
        stage('Test') {
            steps {
                echo "How are you"
            }
        }
        stage('Deploy') {
            steps {
                echo "Fine"
            }
        }
    }
}
